# Generated by Django 5.0.6 on 2025-02-16 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, editable=False, max_length=128)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeasureModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("size", models.CharField(max_length=128)),
                ("milimeters", models.CharField(max_length=128)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubcategoryModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, editable=False, max_length=128)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, editable=False, max_length=128)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="products"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.categorymodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="product.measuremodel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="product.productmodel",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="subcategorymodel",
            constraint=models.UniqueConstraint(
                fields=("name", "slug"), name="subcategory_name_slug"
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="product.subcategorymodel",
            ),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="subcategories",
            field=models.ManyToManyField(
                related_name="categories", to="product.subcategorymodel"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariationmodel",
            constraint=models.UniqueConstraint(
                fields=("product", "measure"), name="product_measure"
            ),
        ),
        migrations.AddConstraint(
            model_name="productmodel",
            constraint=models.UniqueConstraint(
                fields=("name", "slug"), name="product_name_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="categorymodel",
            constraint=models.UniqueConstraint(
                fields=("name", "slug"), name="category_name_slug"
            ),
        ),
    ]
