# Generated by Django 5.0.6 on 2025-02-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariationmodel",
            name="measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="product.measuremodel",
            ),
        ),
        migrations.AlterField(
            model_name="productvariationmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="product.productmodel",
            ),
        ),
    ]
