# Generated by Django 5.0.6 on 2024-05-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
