# Generated by Django 5.0.6 on 2024-07-11 02:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0002_alter_categorymodel_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, max_length=128)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="products"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="front.categorymodel",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="productmodel",
            constraint=models.UniqueConstraint(
                fields=("name", "slug"), name="unique_name_slug"
            ),
        ),
    ]
