# Generated by Django 5.0.6 on 2024-05-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0003_productmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="products"
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
