# Generated by Django 5.0.6 on 2024-07-11 03:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0003_productmodel_productmodel_unique_name_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productmodel",
            name="unique_name_slug",
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="slug",
            field=models.SlugField(blank=True, editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(blank=True, editable=False, max_length=128),
        ),
        migrations.AddConstraint(
            model_name="categorymodel",
            constraint=models.UniqueConstraint(
                fields=("name", "slug"), name="category_name_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="productmodel",
            constraint=models.UniqueConstraint(
                fields=("name", "slug"), name="product_name_slug"
            ),
        ),
    ]
