# Generated by Django 5.0.6 on 2024-07-12 00:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0004_remove_productmodel_unique_name_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubcategoryModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, editable=False, max_length=128)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="subcategorymodel",
            constraint=models.UniqueConstraint(
                fields=("name", "slug"), name="subcategory_name_slug"
            ),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="subcategories",
            field=models.ManyToManyField(
                related_name="categories", to="front.subcategorymodel"
            ),
        ),
    ]
