# Generated by Django 5.0.6 on 2024-07-12 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0005_subcategorymodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="subcategory",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="front.subcategorymodel",
            ),
        ),
    ]
