# Generated by Django 5.0.6 on 2024-07-12 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0006_productmodel_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="front.subcategorymodel",
            ),
        ),
    ]
