# Generated by Django 5.0.6 on 2024-07-14 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0007_alter_productmodel_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasureModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("size", models.CharField(max_length=128)),
                ("milimeters", models.CharField(max_length=128)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="productmodel",
            name="measures",
            field=models.ManyToManyField(
                related_name="products", to="front.measuremodel"
            ),
        ),
    ]
