# Generated by Django 5.0.6 on 2024-08-07 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0008_measuremodel_productmodel_measures"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="variations",
                        to="front.measuremodel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="variations",
                        to="front.productmodel",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="productvariationmodel",
            constraint=models.UniqueConstraint(
                fields=("product", "measure"), name="product_measure"
            ),
        ),
    ]
