# Generated by Django 5.0.6 on 2024-08-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0009_productvariationmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="measures",
        ),
        migrations.RemoveField(
            model_name="productmodel",
            name="stock",
        ),
    ]
