# Generated by Django 5.0.6 on 2024-08-28 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0010_remove_productmodel_measures_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItemModel",
            fields=[
                (
                    "key",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("size", models.CharField(max_length=128)),
                ("stock", models.IntegerField(default=0)),
                ("quantity", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cart_item",
                        to="front.productmodel",
                    ),
                ),
            ],
        ),
    ]
